on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: go install
      - name: Build Linux Binary
        run: env GOOS=linux GOARCH=amd64 go build -o ghoto-linux-amd64
      - name: Build Darwin Binary
        run: env GOOS=darwin GOARCH=amd64 go build -o ghoto-darwin-amd64
      - name: Build Windows Binary
        run: env GOOS=windows GOARCH=amd64 go build -o ghoto-windows-amd64.exe
      - name: Upload assets ghoto-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ghoto-linux-amd64
          asset_name: ghoto-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload assets ghoto-darwin-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ghoto-darwin-amd64
          asset_name: ghoto-darwin-amd64
          asset_content_type: application/octet-stream
      - name: Upload assets ghoto-windows-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ghoto-windows-amd64.exe
          asset_name: ghoto-windows-amd64.exe
          asset_content_type: application/octet-stream